import asyncio
import logging
import random
from .. import loader, utils

logger = logging.getLogger(__name__)


@loader.tds
class Mod(loader.Module):
    strings = {"cfg_doc": "This is what is said, you can edit me with the configurator",
               "name": "TestM"}
    def __init__(self):
        self.config = loader.ModuleConfig("CONFIG_STRING", "hello", lambda m: self.strings("cfg_doc", m))


    @loader.unrestricted
    async def examcmd(self, message):
        await utils.answer(message, "WoW")

    async def pentagoncmd(self, message):
        await utils.answer(message, "Vzlom Pentagona V1")
	await asyncio.sleep(1)
	await utils.answer(message, "Hacking 0%")
	await asyncio.sleep(1)
	await utils.answer(message, "Hacking 1%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 2%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 3%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 4%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 5%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 6%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 7%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 8%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 9%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 10%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 11%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 12%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 13%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 14%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 15%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 16%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 17%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 18%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 19%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 20%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 21%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 22%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 23%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 24%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 25%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 26%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 27%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 28%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 29%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 30%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 31%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 32%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 33%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 34%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 35%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 36%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 37%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 38%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 39%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 40%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 41%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 42%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 43%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 44%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 45%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 46%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 47%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 48%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 49%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 50%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 51%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 52%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 53%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 54%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 55%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 56%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 57%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 58%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 59%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 60%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 61%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 62%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 63%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 64%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 65%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 66%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 67%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 68%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 69%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 70%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 71%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 72%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 73%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 74%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 75%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 76%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 77%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 78%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 79%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 80%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 81%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 82%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 83%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 84%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 85%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 86%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 87%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 88%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 89%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 90%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 91%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 92%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 93%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 94%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 95%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 96%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 97%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 98%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 99%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 100%")
	await asyncio.sleep(0.2)
	await utils.answer(message, "Hacking 101%")
	await asyncio.sleep(2)
	await utils.answer(message, "Pentagon Hacked!")
